// Copyright 2021 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

#ifndef __CORE_MODELS_OUTPUT_FOUNDRY_H__
#define __CORE_MODELS_OUTPUT_FOUNDRY_H__

#include <stdint.h>

#include "core/models/outputs/native_tokens.h"

/**
 * @brief An output type which controls the supply of user defined native tokens.
 *
 */
typedef struct {
  void* address;                  ///< The alias controlling this foundry
  uint64_t amount;                ///< The amount of IOTA tokens held by this output
  native_tokens_t native_tokens;  ///< The native tokens held by this output
  uint32_t serial;                ///< The serial number of the foundry
  void* token_tag;                ///< The tag which is always the last 12 bytes of the tokens generated by this foundry
  void* circulating_supply;       ///< The circulating supply of tokens controlled by this foundry
  void* max_supply;               ///< The maximum supply of tokens controlled by this foundry
  void* token_scheme;             ///< The token scheme used by this foundry
  void* feature_blocks;           ///< The feature flocks which modulate the constrants on this output
} output_foundry_t;

#endif
