/* ===auto-generated by pbkdf2_vectors.py DO NOT EDIT!!=== */

// Copyright 2021 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

#ifndef __TEST_CRYPTO_PBKDF2_H__
#define __TEST_CRYPTO_PBKDF2_H__

#include <stdlib.h>

// PBKDF2 test vectors from https://datatracker.ietf.org/doc/html/rfc6070
typedef struct {
  size_t iter;    ///< iteration
  size_t dk_len;  ///< length of derived key
  char *pwd;      ///< point to the password
  char *salt;     ///< point to the salt
  char *sha1;     ///< derived key from sha1
  char *sha256;   ///< derived key from sha256
  char *sha512;   ///< derived key from sha512
} pbkdf2_vector_t;

// clang-format off
static pbkdf2_vector_t pbkdf2[] = {
  {1, 20,
  "70617373776f7264",
  "73616c74",
  "0c60c80f961f0e71f3a9b524af6012062fe037a6",
  "120fb6cffcf8b32c43e7225256c4f837a86548c9",
  "867f70cf1ade02cff3752599a3a53dc4af34c7a6"},
  {2, 20,
  "70617373776f7264",
  "73616c74",
  "ea6c014dc72d6f8ccd1ed92ace1d41f0d8de8957",
  "ae4d0c95af6b46d32d0adff928f06dd02a303f8e",
  "e1d9c16aa681708a45f5c7c4e215ceb66e011a2e"},
  {4096, 20,
  "70617373776f7264",
  "73616c74",
  "4b007901b765489abead49d926f721d065a429c1",
  "c5e478d59288c841aa530db6845c4c8d962893a0",
  "d197b1b33db0143e018b12f3d1d1479e6cdebdcc"},
  {4096, 25,
  "70617373776f726450415353574f524470617373776f7264",
  "73616c7453414c5473616c7453414c5473616c7453414c5473616c7453414c5473616c74",
  "3d2eec4fe41c849b80c8d83662c0e44a8b291a964cf2f07038",
  "348c89dbcbd32b2f32d814b8116e84cf2b17347ebc1800181c",
  "8c0511f4c6e597c6ac6315d8f0362e225f3c501495ba23b868"},
  {4096, 16,
  "7061737300776f7264",
  "7361006c74",
  "56fa6aa75548099dcc37d7f03425e0c3",
  "89b69d0516f829893c696226650a8687",
  "9d9e9c4cd21fe4be24d5b8244c759665"},
};
// clang-format on

#endif
